import Head from "next/head";

import styles from "../styles/Home.module.css";
import requests from "../utils/requests";
import Header from "./Header";
import Navbar from "./Navbar";
import Results from "./Results";

export default function Home({ results }) {
  console.log(results);
  return (
    <div className={styles.container}>
      <Head>
        <title>Hulu Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Navbar />

        <Results results={results} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const general = context.query.general;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[general]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
